language: node_js
node_js:
  - "4.2"
  - "0.12"
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"

before_install:
  # Upgrade `npm` to avoid semver issues
  - curl --location http://rawgit.com/twolfson/fix-travis-ci/master/lib/install.sh | bash -s

install:
  # Install canvas dependencies
  - sudo apt-get update -y
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++ -y

  # Install node modules
  - npm install

notifications:
  email: false
